baseURL = "https://www.eclipse.org/ecp/emfforms"
DefaultContentLanguage = "en"
title = "EMF Forms"
theme = "syna"

[markup.goldmark.renderer]
unsafe = true

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[params]
  name = "Eclipse Foundation"
  description = "EMF Forms"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    #favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#1190ba"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#025973"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = ""
  name = "Home"
  weight = 10

[[menu.main]]
  url = "gettingstarted"
  name = "Getting started"
  weight = 15

[[menu.main]]
  url = "support"
  name = "Support"
  weight = 20

[[menu.main]]
  url = "documentation"
  name = "Documentation"
  weight = 30

[[menu.main]]
  url = "downloads"
  name = "Downloads"
  weight = 40

[[menu.main]]
  url = "gettinginvolved"
  name = "Getting Involved"
  weight = 50

[[menu.main]]
  url = "contact"
  name = "Contact"
  weight = 60

[[menu.main]]
  url = "https://git.eclipse.org/r/plugins/gitiles/emfclient/org.eclipse.emf.ecp.core"
  name = "Git"
  weight = 60

[[menu.footer]]
  url = "https://jsonforms.io"
  name = "JSON Forms"
  weight = 15

[[menu.footer]]
  url = "https://eclipse.org/ecp"
  name = "EMF Forms"
  weight = 10

[[menu.footer]]
  url = "https://emf.cloud"
  name = "EMF Cloud"
  weight = 5

[[menu.copyright_footer]]
  url = "https://projects.eclipse.org/projects/modeling.emft.emf-client"
  name = "About"
  weight = 5

[[menu.copyright_footer]]
  url = "https://www.eclipse.org/legal/privacy.php"
  name = "Privacy Policy"
  weight = 10

[[menu.copyright_footer]]
  url = "https://www.eclipse.org/legal/termsofuse.php"
  name = "Terms of Use"
  weight = 20

[[menu.copyright_footer]]
  url = "https://www.eclipse.org/legal/copyright.php"
  name = "Copyright"
  weight = 30

[[menu.copyright_footer]]
  url = "https://www.eclipse.org/legal/"
  name = "Legal"
  weight = 40


[[menu.footer_social]]
  weight = 20
  name = "twitter"
  pre = "fab fa-twitter"
  url = "https://twitter.com/emfforms"

  [[menu.footer_social]]
  weight = 30
  name = "Git"
  pre = "fab fa-github"
  url = "https://git.eclipse.org/r/plugins/gitiles/emfclient/org.eclipse.emf.ecp.core"

[[menu.footer_social]]
  weight = 30
  name = "forum"
  pre = "far fa-comments"
  url = "http://www.eclipse.org/forums/index.php/f/19/"
